from gopigo import *  # this has all the functions related to GoPiGo; not sensors
from time import sleep   # Python library that allows us to deal with time

print ("Going Forward")
forward()
sleep(1)
print ("Going Backward")
backward()
sleep(1)
print ("Turning to the left")
left()
sleep(0.5)
print ("Spinning left")
left_rot()
sleep(0.5)
print ("Turning to the right")
right()
sleep(0.5)
print ("Spinning right")
right_rot()
sleep(0.5)
print ("Stopping")
stop()
print ("Faster 1 of 3")
increase_speed()
forward()
sleep(1)
print ("Faster 2 of 3")
increase_speed()
forward()
sleep(1)
print ("Faster 3 of 3")
increase_speed()
forward()
sleep(1)
print ("slower 1 of 3")
decrease_speed()
forward()
sleep(1)
print ("slower 2 of 3")
decrease_speed()
forward()
sleep(1)
print ("slower 3 of 3")
decrease_speed()
forward()
sleep(1)
print ("Stopping")
stop()

